//! Content of the `help.md` buffer.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Line {
    Title(&'static str),
    Heading(&'static str),
    Text(&'static str),
    Key(&'static str, &'static str),
    Blank,
}

use Line::{Blank, Heading, Key, Text, Title};

pub const LINES: &[Line] = &[
    Title("code-racer"),
    Text("Typing practice that looks like your editor. Race your team on the LAN."),
    Blank,
    Heading("everywhere"),
    Key("Ctrl+C", "quit and restore the terminal"),
    Key("Ctrl+B", "show or hide the explorer"),
    Key(":", "command line, Tab completes"),
    Key("?", "this help"),
    Blank,
    Heading("explorer and settings"),
    Key("j k", "move down and up"),
    Key("Enter l", "open or activate"),
    Key("h l", "change a value"),
    Key("i", "edit a text value, Enter saves, Esc cancels"),
    Key("Tab", "switch between the explorer and the editor"),
    Key("Esc", "back to the explorer"),
    Key("s", "start a solo session with the current settings"),
    Key("m", "open race.toml"),
    Key("c", "create a room"),
    Key("q", "quit"),
    Blank,
    Heading("typing"),
    Key("keys", "type the text"),
    Key("Backspace", "delete a character"),
    Key("Ctrl+W", "delete a word, also Alt+Backspace"),
    Key("Enter", "new line, code is indented for you"),
    Key("Ctrl+R", "restart with a new text"),
    Key("Esc", "stop, press it twice to leave a race"),
    Blank,
    Heading("results"),
    Key("r Enter", "new text, or another race when you host"),
    Key("e", "change the practice settings"),
    Key("Esc", "close"),
    Blank,
    Heading("room"),
    Key("r Space", "toggle ready"),
    Key("s", "start the race, host only, once everyone is ready"),
    Key("Esc", "leave the room"),
    Blank,
    Heading("commands"),
    Key(":solo", "start with the current settings"),
    Key(":words 50", "words session (also :time, :quote, :code)"),
    Key(":lang french", "natural or programming language"),
    Key(":e src/lib.rs", "practise on one of your own files"),
    Key(":set punctuation", "also nopunctuation, numbers, nonumbers"),
    Key(":set theme=mono", "editor, dark or mono"),
    Key(":set server=URL", "race server address, ws://host:8080"),
    Key(":set username=Jean", "name shown to other racers"),
    Key(":create", "create a room with the race.toml settings"),
    Key(":join FK72AD", "join a room"),
    Key(":history :config", "open a buffer, also :race and :help"),
    Key(":q", "quit"),
    Blank,
    Heading("statistics"),
    Key("wpm", "correct characters / 5 / minutes"),
    Key("raw", "every typed character / 5 / minutes"),
    Key("accuracy", "correct keystrokes / all keystrokes"),
    Key("errors", "wrong keystrokes, corrected or not"),
    Text("Mistakes must be fixed to finish a text. Typing stops 10 characters"),
    Text("after an uncorrected mistake, so a typo never ruins a whole line."),
];
